### ISSUE TITLE
Conflicting peer dependencies of @powersync/common

### ISSUE THREAD

**Issue by hut36** [powersync-ja/powersync-js#231]
When installing both @powersync/web and @powersync/attachments as dependencies, I ran into this error:

```
dependencies:
+ @powersync/attachments 2.0.10
+ @powersync/web 1.2.1

 WARN  Issues with peer dependencies found
.
├─┬ @powersync/web 1.2.1
│ └── ✕ missing peer @powersync/common@^1.13.01.13.0
└─┬ @powersync/attachments 2.0.10
  └── ✕ missing peer @powersync/common@^1.9.0
✕ Conflicting peer dependencies:
  @powersync/common
```

The latest good @powersync/web version is 1.0.2. I'm using pnpm 8.15.8.

**Comment by hut36** [comment]
Installing only @powersync/web results the same error. The `peerDependencies` in file package.json (https://www.npmjs.com/package/@powersync/web?activeTab=code) looks apparently wrong:

```
  "peerDependencies": {
    "@journeyapps/wa-sqlite": "~0.2.0",
    "@powersync/common": "^1.13.01.13.0"
  },
```

**Comment by DominicGBauer** [comment]
Hi @hut36 apologies for the delay. I am investigating this issue now.

**Comment by DominicGBauer** [comment]
Hi @hut36 this is now resolved in the latest package versions e.g. https://www.npmjs.com/package/@powersync/web?activeTab=code, thanks for pointing this issue out.
