### ISSUE TITLE
powersync diagnostics app: Error: Closed. Original cause [Error: [429] Maximum active concurrent connections limit has been reached

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-js#242]
initial app load worked fine, i just had a few todos and a few lists defined.
then i added a todo, and didn't see it reflected in the rows conut for the todos table (should have jumped from 3 to 4)
then i hit the "clear and redownload" button, and now the app is constantly erroring.
![image](https://github.com/user-attachments/assets/7413b36b-6c97-41ff-be38-ad5ea56ebcb8)

**Comment by stevensJourney** [comment]
This should be fixed by https://github.com/powersync-ja/powersync-js/pull/238. The fix should be included in `@powersync/web@1.2.4`. 

We've also released a service side fix which can be applied by redeploying the PowerSync instance. Triggering a deploy should also clear any stale connections.

**Comment by Dieterbe** [comment]
thanks steven!
