### ISSUE TITLE
Support `TableV2` in Schema of `@powersync/common`

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/powersync-js#250]
`Schema` should be compatible with TableV2, right now it's only with `Table`. https://github.com/powersync-ja/powersync-js/blob/main/packages/common/src/db/schema/Schema.ts#L19

## Steps to reproduce it

I updated the type Table to TableV2 of `@powersync/common@1.14.0` (my code https://github.com/guillempuche/localfirst_react_server/blob/main/packages/core/src/to_schema.effect.ts#L25)

![image](https://github.com/user-attachments/assets/f4279263-ab54-4524-b6f4-f2ad2e6b3a98)

```ts
export function toPowerSyncSchema<Tables extends Record<string, S.Schema.Any>>(
	tables: Tables,
): Schema {
	return new Schema(
		Object.entries(tables).map(([name, table]) => {
			const properties = AST.getPropertySignatures(
				isColumnTypes(table)
					? S.encodedSchema(table.select).ast
					: S.encodedSchema(table).ast,
			)

			// return new Table({
			// 	name,
			// 	columns: properties.map(toPowerSyncColumn),
			// })
			return new TableV2({
				options: { name },
				columns: properties.map(toPowerSyncColumn),
			})
		}),
	)
}
```

**Comment by DominicGBauer** [comment]
@guillempuche Schema is compatible with TableV2 as shown here https://github.com/powersync-ja/powersync-js/blob/main/demos/react-supabase-todolist/src/library/powersync/AppSchema.ts. 

It seems that you are passing in a TableV2 array but it is actually expecting an object with TableV2's E.g.

```
const todos = new TableV2(
  {
    list_id: column.text,
    created_at: column.text,
    completed_at: column.text,
    description: column.text,
    created_by: column.text,
    completed_by: column.text,
    completed: column.integer
  },
  { indexes: { list: ['list_id'] } }
);

const lists = new TableV2({
  created_at: column.text,
  name: column.text,
  owner_id: column.text
});

export const AppSchema = new Schema({
  todos,
  lists
});
```

**Comment by guillempuche** [comment]
With `Table` works.

`Schema` expects a `Table[]`. I'm providing `TableV2<ColumnsType>[]`, but Schema doesn't accept it.

```
Argument of type 'TableV2<ColumnsType>[]' is not assignable to parameter of type 'SchemaType | Table[]'.
  Type 'TableV2<ColumnsType>[]' is not assignable to type 'Table[]'.
    Type 'TableV2<ColumnsType>' is missing the following properties from type 'Table': name, viewNameOverride, viewName, localOnly, and 5 more.ts(2345)
```

**Comment by DominicGBauer** [comment]
The problem is Object.entries(...).map is returning an array. So when you 
```
		return new TableV2({
				options: { name },
				columns: properties.map(toPowerSyncColumn),
			})
```
You are returning an array of TableV2's or TableV2[]. 

Schema is defined like this 
```Schema<SchemaType>(tables: Table[] | SchemaType): Schema<SchemaType>```.

So you can either pass a Table[] or the SchemaType. Therefore if you send an array of TableV2's it is going to try to match Table[] to TabeleV2[] which will throw an error since they are different.

You need to convert the Object.entries(...).map() into a Record of Table V2's. So something like this (I haven't explicitly tested this so might need some adjustments)

export function toPowerSyncSchema<Tables extends Record<string, S.Schema.Any>>(
  tables: Tables
): Schema {
  return new Schema(
    Object.fromEntries(
      Object.entries(tables).map(([name, table]) => {
        const properties = AST.getPropertySignatures(
          isColumnTypes(table)
            ? S.encodedSchema(table.select).ast
            : S.encodedSchema(table).ast
        );

        // Return an entry of the form [name, TableV2]
        return [
          name,
          new TableV2(
            {
              columns: properties,
            },
            {
              viewName: name,
            }
          ),
        ];
      })
    )
  );
}

**Comment by guillempuche** [comment]
Thanks a lot Dominic! Just a small tweak to your solution solved it.

```ts
		Object.fromEntries(
			Object.entries(tables).map(([name, table]) => {
				const properties = AST.getPropertySignatures(
					isColumnTypes(table)
						? S.encodedSchema(table.select).ast
						: S.encodedSchema(table).ast,
				)
				
				// HERE is the small tweak for `columns` 
				const columns: ColumnsType = {}
				for (const property of properties) {
					if (typeof property.name === 'string') {
						columns[property.name] = {
							type: toPowerSyncColumnType(property.type),
						}
					}
				}

				return [
					name,
					new TableV2(columns, {
						viewName: name,
					}),
				]
			}),
		),
	)
```
