### ISSUE TITLE
Server sync not working

### ISSUE THREAD

**Issue by J05HI** [powersync-ja/powersync-js#258]
I am currently testing the "vue-supabase-todolist" demo.
I have set everything up as in the docs.
Register/login works fine. Offline usage too. Only problem is, that it does not sync with the online PowerSync instance.
Have I missed anything?

![Screenshot 2024-08-08 16-54-26](https://github.com/user-attachments/assets/6702bf59-b111-4670-ada5-30098d8bf54d)

**Comment by Chriztiaan** [comment]
Hey @J05HI, this could be that you skipped a step wild setting up your powersync service instance. There's a step to enable supabase's auth. See https://docs.powersync.com/usage/installation/authentication-setup/supabase-auth for this.

**Comment by Chriztiaan** [comment]
Cool @J05HI . Then next up would be to check the error, last time I got that I needed to generate a new JWT secret on my supabase instance. This is often an issue when a supabase instance is paused.

**Comment by Chriztiaan** [comment]
Awesome! I am glad you're sorted :)
