### ISSUE TITLE
Unable to resolve "fast-base64-decode" for React Native

### ISSUE THREAD

**Issue by cloudandcode** [powersync-ja/powersync-js#273]
![image](https://github.com/user-attachments/assets/a40205ad-6b5f-480d-926d-2ac979dfa970)

Looks like your dev dependency for "fast-base64-decode" should be shifted to an actual dependency for @powersync/react-native v1.10.1.

Adding this module to my app's package.json resolved the issue.

**Comment by Chriztiaan** [comment]
Hey @cloudandcode, because we bundle our dependencies I don't think this should be needed. I'll test this on my side soon.

**Comment by Chriztiaan** [comment]
Hey @cloudandcode, I tested a standalone copy of our react-native-supabase-todolist with the latest releases of `@powersync/react-native` with both npm and pnpm and it seemed to work. Could I ask for a copy of your package.json? Might be worth nuking your lock file/node_modules and doing a fresh install to confirm the problem on your side.

**Comment by cloudandcode** [comment]
@Chriztiaan good call re: nuking node_modules, thanks mate - I should have reached for that option first :)

**Comment by Chriztiaan** [comment]
Good to hear!
