### ISSUE TITLE
Support for Kysely plugins

### ISSUE THREAD

**Issue by bviebahn** [powersync-ja/powersync-js#292]
Using Kysely plugins doesn't seem to be properly supported by the react package. I am using the `ParseJSONResultsPlugin`, and it works when I call `execute` on the query, but not when I pass the query to the useQuery hook.

I guess this is a bug rather than a feature request, because:
- The types of `wrapPowerSyncWithKysely` suggest kysely can be configured as usual using the second config parameter. (On another note: I think the config parameter should be changed to `Omit<KyselyConfig, 'dialect'>`, since `dialect` is set by `wrapPowerSyncWithKysely` and I'm not sure it ever makes sense to override it. At least it should be optional)
- Kysely seems to assume specific plugins to be used. For example `jsonArrayFrom` and `jsonObjectFrom` assume to be used with `ParseJSONResultsPlugin`, so the types will be wrong if the plugin doesn't work.

**Comment by stevensJourney** [comment]
This is probably due to us calling `.compile` on the supplied Kysely query to get the SQL and query parameters. We don't explicitly call `.execute` on the Kysely query. I'm assuming the `.execute` call should allow the plugins to map column data. We can investigating supporting `.execute`

**Comment by guillempuche** [comment]
This means I can't use https://kysely-org.github.io/kysely-apidoc/classes/CamelCasePlugin.html for now, right?

**Comment by stevensJourney** [comment]
> This means I can't use https://kysely-org.github.io/kysely-apidoc/classes/CamelCasePlugin.html for now, right?

Most likely. This will be fixed soon.

**Comment by guillempuche** [comment]
I love the team's speed for improvements!

**Comment by guillempuche** [comment]
Reminder: this will help to convert [Temporal datetimes](https://github.com/fullcalendar/temporal-polyfill) via a plugin. More here https://discord.com/channels/1138230179878154300/1282584951656550473/1282671991005909072

**Comment by stevensJourney** [comment]
Closing this issue as plugins should be supported from `@powersync/kysely-driver@0.4.0`
