### ISSUE TITLE
diagnostics app shows infinite spinner and empty schema, when data doesn't replicate

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-js#304]
i was trying to use the diagnostics app at https://diagnostics-app.powersync.com/sync-diagnostics
the 'tables' spinner just kept spinning and the schema stayed empty

i then realized my postgres publication wasn't setup correctly (hence i was trying to use the diagnostics app, because i didn't see any data in my flutter app and wanted to debug it)

once i setup the publication, data flowed, and the diagnostics app worked.

so, my suggestion: handle this scenario more gracefully in the diagnostics app and aid the user in understanding what might be wrong if no data is flowing

**Comment by stevensJourney** [comment]
I agree that this kind of feedback would be valuable. Achieving this result will require some work on both the PowerSync service and clients. For now we are tracking this request in our Engineering Backlog.

**Comment by rkistner** [comment]
The issue of the table spinner showing indefinitely in that case was fixed recently (it will just display an empty table now).

We still need to do more to make it easier to diagnose _why_ there is no data, especially for self-hosted instances, but we can track that separate.

**Comment by rkistner** [comment]
I believe the issue was already fixed in https://github.com/powersync-ja/powersync-js/pull/289, but the update was only deployed to the hosted diagnostics app a while later.
