### ISSUE TITLE
diagnostics app : clarify "This is based on downloaded data, rather than the source database." ?

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-js#307]
it's not clear what this means.
as a developer, i care about whether the following flow works:
- set up sync rule
- copy paste schema from diagnostics app into my own code base
- build the corresponding models & code in my code base.

is the schema good enough for this, or do i need to worry about certain fields not showing up? when? is this because of columns that can be null, or other cases?

**Comment by stevensJourney** [comment]
The diagnostics app is only intended for diagnosing sync rules from the perspective of a client. The schema generated here is a convenience, or sanity check, of the data (in specific tables) which the user effectively will have access to given the current data set. 

As you mentioned, if a certain table contains no data then it won't be shown in the dynamically generated schema. 

This schema should not be used as a source of truth when developing you application. 

For instances hosted by us the Dashboard's schema generation should be used instead. We don't currently have a nice tool for this in self hosted environments.

**Comment by Dieterbe** [comment]
yes but somebody implementing powersync and looking at the diagnostic app will usually not understand what "based on downloaded data" means exactly. Perhaps this could mention that download data means "any columns that were seen, and not-null, in the rows that were downloaded because they matched the sync rules". (at least that's my understanding thus far)

**Comment by LucDeCaf** [comment]
@Dieterbe I made a [pull request here](https://github.com/powersync-ja/powersync-js/pull/328) to 1. update the generated schema and 2. provide clarity on what exactly is meant by the schema being based on "downloaded data," LMK if this is what you're looking for 👍

**Comment by Dieterbe** [comment]
It is

**Comment by benitav** [comment]
Thanks for the feedback and assist @Dieterbe and @LucDeCaf - merged the PR to address this.
