### ISSUE TITLE
tool that converts postgres schema into schema in dart and other SDK syntaxes

### ISSUE THREAD

**Issue by Dieterbe** [powersync-ja/powersync-js#308]
considering that using the diagnostics app is not ideal as a source of truth for the schema (see #306, #307), it would be nice if there was a simple CLI tool that either would login to postgres directly, or could read the output from postgres describe commands into its stdin,
and generates the correct schema syntax that can be copy pasted into a codebase (e.g. in dart, or other languages)

**Comment by stevensJourney** [comment]
We will add this as a feature request on our Product board.

**Comment by benitav** [comment]
Closing this here - we're tracking this internally.
