### ISSUE TITLE
hasSynced status not being reset on disconnectAndClear

### ISSUE THREAD

**Issue by shelley-xyris** [powersync-ja/powersync-js#310]
Hello,
      
I believe this issue has been previously [fixed for the Flutter client](https://github.com/powersync-ja/powersync.dart/pull/139) but not for React. I need to reference the hasSynced or lastSyncedAt status when a user first logs into the app and this works as expected until the user logs out and then into a different account. The hasSynced is still set to true even after calling disconnectAndClear.

**Comment by Chriztiaan** [comment]
Hey @shelley-xyris, I have just retested this in both the react-supabase-todolist and react-native-supabase-todolist demos and it seems to be working. We implemented a similar fix to the flutter client in this [PR](https://github.com/powersync-ja/powersync-js/pull/261) around mid-august. Is it possible that you are using an older library version?

**Comment by kobiebotha** [comment]
@shelley-xyris any feedback for us on this perhaps? Otherwise we'll mark as resolved in a few days.

**Comment by shelley-xyris** [comment]
It does appear to be resolved, thank you
