### ISSUE TITLE
Error [Not at a consistent checkpoint - cannot update local db] when running react-native-supabase-todolist

### ISSUE THREAD

**Issue by nthtrung09it** [powersync-ja/powersync-js#322]
I ran the source **react-native-supabase-todolist**, but saw the error log:

![CleanShot 2024-09-29 at 10 25 12@2x](https://github.com/user-attachments/assets/3aeee9eb-ec41-4e1c-8028-bad4727e35e6)

> DEBUG  [PowerSyncStream] Checkpoint complete {"buckets": [{"bucket": "user_lists[\"d727e9f8-3fa9-4cb3-b14c-715fe8a74da2\"]", "checksum": -1366502408, "count": 2}, {"bucket": "user_lists[\"c021e243-f121-4341-8749-5c9b43c86391\"]", "checksum": 572786632, "count": 6}, {"bucket": "user_lists[\"fab167a0-09db-4b0a-b303-cdc4aea2ac9d\"]", "checksum": 977374437, "count": 1}, {"bucket": "user_lists[\"05d32f2a-39d0-4a79-9c9b-1f0dccde481e\"]", "checksum": 1909264827, "count": 1}], "last_op_id": "270"}
> DEBUG  [SqliteBucketStorage] validateChecksums result item {"result": "{\"valid\":true,\"failed_buckets\":[]}"}
> DEBUG  [SqliteBucketStorage] Not at a consistent checkpoint - cannot update local db
> DEBUG  [PowerSyncStream] Caught exception when uploading. Upload will retry after a delay. Exception: Received 404 -  when getting from /write-checkpoint2.json?client_id=bda2e5be-87c9-4b63-a690-61fecb280c93: {"message":"Route GET://write-checkpoint2.json?client_id=bda2e5be-87c9-4b63-a690-61fecb280c93 not found","error":"Not Found","statusCode":404}}

When I did a fresh install the app, logined and then updated data on supabase tables, changes **synced** to ios app.
But when I started to change something in my ios app (create new list), changes from ios app synced to my supabase tables, but changes from supabase tables did not sync to my ios app.

The web project (react-supabase-todolist) does not encounter that issue.

Here is the video: [powersync_supabase_ios_sync_error](https://www.icloud.com/iclouddrive/0bfhjfabK-XETMRr6TC5tEIRA#powersync%5Fsupabase%5Fios%5Fsync%5Ferror)

**Comment by stevensJourney** [comment]
It looks like the `GET` request to `//write-checkpoint2.json` is failing. I believe this is due to there being an additional `/` in the POWERSYNC_URL environment variable. 

Could you try removing any additional `/`s and confirm if that solves the issue for you?

**Comment by nthtrung09it** [comment]
@stevensJourney yes, after removing the / in my powersyncUrl, it works. Thank you very much.
