### ISSUE TITLE
[Feature/React] Support for dynamic dependencies in `useQuery`

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/powersync-js#323]
Currently, `useQuery` in PowerSync throws the following warning when the dependencies change dynamically:
```
Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [01923dca-8707-744a-a214-d69e099b9a83]
```
This issue arises when `useQuery`'s dependency changes from `null` to a valid value, which is a common pattern in React when dealing with conditional data fetching based on asynchronous or optional data sources.

#### **React Hooks Example:**
React allows handling such scenarios using `useEffect` and `useState`:
```tsx
import React, { useEffect, useState } from 'react';

// Simulate an asynchronous fetch function
const fetchData = async (creatorId: string) => {
  return `Data for creatorId: ${creatorId}`;
};

const ExampleComponent = () => {
  const [creator, setCreator] = useState<{ id: string } | null>(null);
  const [data, setData] = useState<string | null>(null);

  // Simulate setting the creator asynchronously
  useEffect(() => {
    setTimeout(() => {
      setCreator({ id: '01923dca-8707-744a-a214-d69e099b9a83' });
    }, 1000);
  }, []);

  useEffect(() => {
    if (creator) {
      fetchData(creator.id).then(setData);
    }
  }, [creator]);

  return (
    <div>
      <p>{data ? data : 'Loading...'}</p>
    </div>
  );
};
```

In this example, React's `useEffect` handles the asynchronous change of `creator` correctly without any warnings when `creator` changes from `null` to an object.

#### **Problem:**
In my case, I use `useQuery` with `creator.value.id` obtained from an authentication hook:
```tsx
const { creator } = useAuth();

const { data: platforms, isLoading: isLoadingPlatforms } = useQuery(
  Option.isSome(creator)
    ? RuntimeClient.runSync(RepoPlatform.getList({ creatorId: creator.value.id }))
    : undefined, // or ' '
);
```
When `creator` is initially `null` and later resolves to a valid object, `useQuery` throws the warning because its dependency array changes size from `[]` to `[creator.value.id]`.

PowerSync's current implementation does not handle such dynamic dependencies correctly, limiting its flexibility in handling real-world scenarios where dependencies can resolve asynchronously or conditionally.

#### **Proposed Solution:**
Allow `useQuery` to handle dynamic dependency arrays without throwing a warning, ensuring that it works seamlessly with standard React hook patterns where dependency values are resolved asynchronously.

**Comment by Chriztiaan** [comment]
Hey @guillempuche, can you confirm that this has been resolved on your side if you use the latest version?

**Comment by guillempuche** [comment]
I'll do it, give me some days

**Comment by guillempuche** [comment]
Many queries in my React components depend on `creator.id` or multiple `profile.id`. I have a hook to provide the ids, instead of passing them as a prop to the component. The question is: how can I pass to useQuery` the ids (when they aren't `undefined`)?

```tsx
export const PageSettings = () => {
	const { creator, isLoading } = useAuth()
	const { data: platforms, isLoading: isLoadingPlatforms } = useQuery(
		creator !== undefined
			? RepoPlatform.getList({ creatorId: creator.id }) // A Kysely query
			: undefined
	)
```

**Comment by Chriztiaan** [comment]
@guillempuche, I am not sure I am following your question. Is this a question specific for when you use `kysely` with `useQuery`? What would it have looked like if you weren't using `kysely` query here?

I suspect that this isn't an issue with the mentioned fix, correct?

**Comment by guillempuche** [comment]
You're right, it's a follow-up topic.

**Comment by guillempuche** [comment]
How can I do this?
If I do `useQuery(some ? kysely : ' ')`, it complains `Failed to fetch tables: Error: incomplete input`

> ```tsx
> export const PageSettings = () => {
> 	const { creator, isLoading } = useAuth()
> 	const { data: devices, isLoading: isLoadingDevices } = useQuery(
> 		creator !== undefined
> 			? RepoDevices.getList({ creatorId: creator.id }) // A Kysely query
> 			: undefined
> 	)
> ```

**Comment by Chriztiaan** [comment]
So in the case of `undefined`, we don't want to actually run the query right? The hook doesn't support a disabled state and it assumes that if it's invoked that is should try to execute with the input.
So the straight forward options could be:
1. Don't render this component if the creator is not available yet
2. Use `@powersync/tanstack-react-query`'s implementation of `useQuery` which allows you to manage whether a query should execute via `enabled` see [here](https://tanstack.com/query/latest/docs/framework/react/reference/useQuery) 
3. Potentially wrap the hook and add that functionality 🤔

**Comment by rkistner** [comment]
It's not the cleanest, but you can use a query like `select 0 where 0` instead of `undefined` - that will still execute once but return no results.

**Comment by guillempuche** [comment]
Perfect.
I'll try both options: SELECT and Tanstack.
