### ISSUE TITLE
Unsupported PowerSync Extension Version Error When Connecting via React/Web Library

### ISSUE THREAD

**Issue by RamDurgaSai** [powersync-ja/powersync-js#329]
We are encountering an issue when attempting to connect to the PowerSync server using the React/Web library. Although the connection works perfectly via the diagnostic app, it fails with the following error when trying through the React/Web library:

```bash
index.js:1
Uncaught (in promise) Error: Unsupported powersync extension version. Need ^0.2.0, got: 0.1.6/308ca1d0
    at PowerSyncDatabase._loadVersion (index.js:1:22077)
    at async PowerSyncDatabase.initialize (index.js:1:21389)
    at async PowerSyncDatabase.waitForReady (index.js:1:21073)
    at async PowerSyncDatabase.connect (index.js:1:22944)
Promise.then
```
Library Versions:

```json
"@powersync/react": "^1.3.7",
"@powersync/web": "^1.3.0"
```

**Comment by Chriztiaan** [comment]
Hey @RamDurgaSai, what version of `wa-sqlite` do you have?
Could you try "@journeyapps/wa-sqlite": "^0.3.0"?

**Comment by RamDurgaSai** [comment]
The Current version is

```json
    "@journeyapps/wa-sqlite": "^0.2.0"
```
will try with 0.3.0 and updates you @Chriztiaan . 

Thanks for quick support.

**Comment by rkistner** [comment]
@shahjahanpak See #339.

**Comment by shahjahanpak** [comment]
@rkistner Thank you sir

**Comment by shahjahanpak** [comment]
Yes sir

**Comment by stevensJourney** [comment]
Glad to hear :). Marking as closed.
