### ISSUE TITLE
Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

### ISSUE THREAD

**Issue by wogno** [powersync-ja/powersync-js#340]
We work on electron forge in production app, we worked to app offline mode but after installed package

  "@hookform/resolvers": "^3.9.0",
    "@journeyapps/wa-sqlite": "^0.4.0",
    "@powersync/kysely-driver": "^0.4.2",
    "@powersync/react": "^1.4.5",
    "@powersync/tanstack-react-query": "^0.0.1",
    "@powersync/web": "^1.8.2",
    
    We git  error Top-level await is not available in package bson that we never installed, so, we don't know where is issue. 

able in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides) 

<img width="1166" alt="Capture d’écran 2024-10-11 à 20 25 44" src="https://github.com/user-attachments/assets/7b7991ce-a226-4186-8573-8160a548e897">

**Comment by stevensJourney** [comment]
Could you try enabling the `vite-plugin-toplevel-await` plugin as in [this](https://github.com/powersync-ja/powersync-js/blob/aad9ba5c0fc2cf487589f4f35eb076a10a30dd92/demos/react-supabase-todolist/vite.config.mts#L2) example?

**Comment by wogno** [comment]
Thanks that worked
