### ISSUE TITLE
Feature request: Add ability to pass encryptionKey into op-sqlite

### ISSUE THREAD

**Issue by nthtrung09it** [powersync-ja/powersync-js#350]
How can I initialize the op-sqlite with encryptionKey to enable sqlcipher?
And can you update to op-sqlite 9.2.1, it uses the newest sqlite and sqlcipher version.

**Comment by mugikhan** [comment]
Hey @nthtrung09it this has been released in `"@powersync/op-sqlite": "^0.4.0"`. Let us know if you have any issues with setting up the encryption.

**Comment by nthtrung09it** [comment]
hi @stevensJourney @mugikhan I've just updated to @powersync/op-sqlite v0.0.4 and it works. Thank you very much.
