### ISSUE TITLE
Page to explain how you manage foreign key

### ISSUE THREAD

**Issue by wogno** [powersync-ja/powersync-js#359]
It's possible to  row with a relationship ?
Exemple:
  invoice -> productItems
                -> clients
               -> Taxes

**Comment by Chriztiaan** [comment]
Yes @wogno, you can look at the [react-supabase-todolist](https://github.com/powersync-ja/powersync-js/tree/main/demos/react-supabase-todolist) demo which shows how to setup sync rules to correctly sync the data and query the relations in the client db.
