### ISSUE TITLE
Question: How can I retrieve the op-sqlite connection to read/write my own tables

### ISSUE THREAD

**Issue by nthtrung09it** [powersync-ja/powersync-js#363]
I'm using PowerSyncJS with op-sqlite and want to have some tables that always remain on the user’s device (never synced), such as the current playing tracks.

What’s the best way to obtain a database connection to read/write data for these tables? Is it safe to open a new connection directly with the SQLite database file for reading/writing?

I noticed there's a locking mechanism in your code, and I'm unsure how to handle this for my use case.

**Comment by mugikhan** [comment]
Hey @nthtrung09it for tables that you do not want to sync we recommend using local-only tables defined in your AppSchema. You can find out more about it here: https://docs.powersync.com/usage/use-case-examples/offline-only-usage.

**Comment by nthtrung09it** [comment]
Thank you @mugikhan. I will check it.
