### ISSUE TITLE
SQL execution error: no such function: json_build_object

### ISSUE THREAD

**Issue by shahjahanpak** [powersync-ja/powersync-js#367]
I am trying to run the following query which contains certain `json functions` and `joins`. I wonder if these are supported with PowerSync as I get this error `Failed to fetch tables: [Error: [react-native-quick-sqlite] SQL execution error: no such function: json_build_object]`

```sql
SELECT
  m.*,
  json_agg(
    json_build_object(
      'name',
      g.name,
      'items',
      (
        SELECT
          json_agg(
            json_build_object('id', i.id, 'name', i.name, 'price', i.price)
          )
        FROM
          group_items gi
          JOIN items i ON gi.item_id = i.id
        WHERE
          gi.group_id = g.id
      )
    )
  ) AS groups
FROM
  menus m
  JOIN menu_groups mg ON mg.menu_id = m.id
  JOIN groups g ON mg.group_id = g.id
GROUP BY
  m.id
```
#### Packages
`@powersync/react-native 1.13.0`
`@journeyapps/react-native-quick-sqlite 1.4.0`
`react-native 0.73.4`
`expo 50.0.6`

**Comment by shahjahanpak** [comment]
This opens the door for another error, `[Error: PowerSync failed to fetch data: [react-native-quick-sqlite] SQL execution error: no such function: json_agg]`.

**Comment by stevensJourney** [comment]
`json_agg` is also not listed on the SQLite3 JSON1 [API](https://www.sqlite.org/json1.html). I haven't verified your use-case, but you might be able to use some combination of `json_group_array` or `json_group_object`.

**Comment by shahjahanpak** [comment]
@stevensJourney It worked. Thanks for the suggestion.

**Comment by stevensJourney** [comment]
Glad to hear :) . I'll close this then.
