### ISSUE TITLE
Mongodb: sync_rules with parameters not working

### ISSUE THREAD

**Issue by amjadbouhouch** [powersync-ja/powersync-js#385]
Hello & thank all of you powersync team!

I'm testing PowerSync with MongoDB &

I've encountered an issue where sync rules don’t seem to work as expected when adding parameters. 

Here’s a quick summary

### Working Example

```yml
bucket_definitions:

  user_data_bucket:

    data:
      - SELECT _id as id, * FROM messages
      
```
### Not Working with Parameters

```yml

bucket_definitions:
  user_data_bucket:
    accept_potentially_dangerous_queries: true
    parameters: 
      - SELECT request.user_id() as user_id
    data:
      - SELECT _id as id, * FROM messages WHERE user = bucket.user_id

```

### Logs

I got fatal errors `Failed to update sync rules from configuration keyword not supported here`

```
powersync-1      | {"errors":[{"location":{"end":797,"start":793},"source":{"location":{"end":44,"start":40},"sql":"SELECT _id as id, * FROM messages WHERE user = bucket.user_id","type":"fatal"},"type":"fatal"}],"level":"error","message":"Failed to update sync rules from configuration keyword not supported here","name":"Replicator:mongodb-database-test","stack":"Error: keyword not supported here\n    at SqlSyncRules.throwOnError (file:///app/packages/sync-rules/dist/SqlSyncRules.js:138:19)\n    at SqlSyncRules.fromYaml (file:///app/packages/sync-rules/dist/SqlSyncRules.js:132:19)\n    at MongoBucketStorage.updateSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:120:37)\n    at MongoBucketStorage.configureSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:74:53)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChangeStreamReplicator.runLoop (file:///app/packages/service-core/dist/replication/AbstractReplicator.js:113:34)","timestamp":"2024-11-05T13:08:08.845Z"}
```

### Rest of logs

```
powersync-1      | {"level":"info","message":"Configuring telemetry.","timestamp":"2024-11-05T13:08:08.824Z"}
powersync-1      | {"level":"info","message":"Attention:\nPowerSync collects completely anonymous telemetry regarding usage.\nThis information is used to shape our roadmap to better serve our customers.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://docs.powersync.com/self-hosting/telemetry\nAnonymous telemetry is currently: enabled","timestamp":"2024-11-05T13:08:08.824Z"}
powersync-1      | {"level":"info","message":"Sharing anonymous telemetry","timestamp":"2024-11-05T13:08:08.824Z"}
powersync-1      | {"level":"info","message":"Telemetry configuration complete.","timestamp":"2024-11-05T13:08:08.827Z"}
powersync-1      | {"level":"info","message":"service started","timestamp":"2024-11-05T13:08:08.828Z"}
powersync-1      | {"level":"info","message":"Sync rules updated from configuration","timestamp":"2024-11-05T13:08:08.829Z"}
powersync-1      | {"errors":[{"location":{"end":797,"start":793},"source":{"location":{"end":44,"start":40},"sql":"SELECT _id as id, * FROM messages WHERE user = bucket.user_id","type":"fatal"},"type":"fatal"}],"level":"error","message":"Failed to update sync rules from configuration keyword not supported here","name":"Replicator:mongodb-database-test","stack":"Error: keyword not supported here\n    at SqlSyncRules.throwOnError (file:///app/packages/sync-rules/dist/SqlSyncRules.js:138:19)\n    at SqlSyncRules.fromYaml (file:///app/packages/sync-rules/dist/SqlSyncRules.js:132:19)\n    at MongoBucketStorage.updateSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:120:37)\n    at MongoBucketStorage.configureSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:74:53)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChangeStreamReplicator.runLoop (file:///app/packages/service-core/dist/replication/AbstractReplicator.js:113:34)","timestamp":"2024-11-05T13:08:08.845Z"}
powersync-1      | {"level":"info","message":"Initial replication already done","timestamp":"2024-11-05T13:08:08.860Z"}
powersync-1      | {"level":"info","message":"Resume streaming at new Timestamp({ t: 1730811586, i: 4003 }) / 672a16c200000fa3","timestamp":"2024-11-05T13:08:08.866Z"}
```

**Comment by Chriztiaan** [comment]
Hey @amjadbouhouch, could you try `messages.user` instead of `user`?

**Comment by amjadbouhouch** [comment]
hey @Chriztiaan  and thanks for your quick response!

I change it but no luck

this is what I got now 
`powersync-1      | {"errors":[{"location":{"end":444,"start":443},"source":{"offset":12,"token":{"_location":{"end":55,"start":54},"col":55,"line":1,"lineBreaks":0,"offset":54,"text":"=","type":"op_eq","value":"="}},"type":"fatal"}],"level":"error","message":"Failed to update sync rules from configuration Syntax error at line 1 col 55:\n\n1  SELECT _id as id, * FROM messages WHERE messages.user = bucket.user_id\n                                                         ^\nUnexpected op_eq token: \"=\". Instead, I was expecting to see one of the following:\n\n    - A \"dot\" token\n    - A \"lparen\" token\n    - A \"kw_array\" token\n    - A \"lbracket\" token\n    - A \"string\" token\n    - A \"eString\" token\n\n","name":"Replicator:mongodb-winshot-29-10-2024","stack":"Error: Syntax error at line 1 col 55:\n\n1  SELECT _id as id, * FROM messages WHERE messages.user = bucket.user_id\n                                                         ^\nUnexpected op_eq token: \"=\". Instead, I was expecting to see one of the following:\n\n    - A \"dot\" token\n    - A \"lparen\" token\n    - A \"kw_array\" token\n    - A \"lbracket\" token\n    - A \"string\" token\n    - A \"eString\" token\n\n\n    at SqlSyncRules.throwOnError (file:///app/packages/sync-rules/dist/SqlSyncRules.js:113:19)\n    at SqlSyncRules.fromYaml (file:///app/packages/sync-rules/dist/SqlSyncRules.js:107:19)\n    at MongoBucketStorage.updateSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:105:37)\n    at MongoBucketStorage.configureSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:59:53)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChangeStreamReplicator.runLoop (file:///app/packages/service-core/dist/replication/AbstractReplicator.js:61:34)","timestamp":"2024-11-05T15:50:18.034Z"}
`

**Comment by Chriztiaan** [comment]
Do you get the same issue for `where "user" = ...`?

**Comment by amjadbouhouch** [comment]
powersync logs show the user id I even hardcoded it

`powersync-1      | {"client_id":"26b89308-f244-467e-a2b7-f254b6e3265b","data_synced_bytes":11070470,"level":"info","message":"Sync stream complete","operations_synced":21000,"timestamp":"2024-11-05T15:57:21.767Z","user_agent":"powersync-js/1.20.1 powersync-react-native react-native/0.74 android/34","user_id":"65aa47430c13e7254cc186c1"}`

```yml
# https://docs.powersync.com/usage/sync-rules/example-global-data
bucket_definitions:
  
  user_data_bucket:
    accept_potentially_dangerous_queries: true
    # https://docs.powersync.com/usage/sync-rules/advanced-topics/client-parameters
    #parameters: SELECT request.parameters() ->> 'user_id' as user_id
    # parameters: 
    #   - SELECT request.user_id() as user_id
    data:
      - SELECT _id as id, * FROM messages where user='65aa47430c13e7254cc186c1'
```
output

`powersync-1      | {"errors":[{"location":{"end":437,"start":433},"source":{"location":{"end":44,"start":40},"sql":"SELECT _id as id, * FROM messages where user='65aa47430c13e7254cc186c1'","type":"fatal"},"type":"fatal"}],"level":"error","message":"Failed to update sync rules from configuration keyword not supported here","name":"Replicator:mongodb-winshot-29-10-2024","stack":"Error: keyword not supported here\n    at SqlSyncRules.throwOnError (file:///app/packages/sync-rules/dist/SqlSyncRules.js:113:19)\n    at SqlSyncRules.fromYaml (file:///app/packages/sync-rules/dist/SqlSyncRules.js:107:19)\n    at MongoBucketStorage.updateSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:105:37)\n    at MongoBucketStorage.configureSyncRules (file:///app/packages/service-core/dist/storage/MongoBucketStorage.js:59:53)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChangeStreamReplicator.runLoop (file:///app/packages/service-core/dist/replication/AbstractReplicator.js:61:34)","timestamp":"2024-11-05T16:00:44.583Z"}`

**Comment by Chriztiaan** [comment]
Sorry I mean:
```
data:
      - SELECT _id as id, * FROM messages WHERE "user" = bucket.user_id
```

**Comment by amjadbouhouch** [comment]
now it works fine!
 
but why!

**Comment by Chriztiaan** [comment]
I suspect `user` is picked up as a keyword. Unlucky that you had that column/key name. I am glad to hear it works :)
Personally, I would name these as `user_id` anyway but I realise that might not always be possible.

**Comment by amjadbouhouch** [comment]
Thank you again for your time & your explanation & all powersync.

I'll keep that in mind. :)
