### ISSUE TITLE
Error Tanstack Query Integration 

### ISSUE THREAD

**Issue by rizalalfandi123** [powersync-ja/powersync-js#417]
Error when not pass parameters in use useQuery

error code :
`   const { data: listRecords = [] } = useQuery({
        queryKey: ["list"],
        query: db.selectFrom("lists").selectAll(),
    });
`

no error with

`const { data: listRecords = [] } = useQuery({
        queryKey: ["list"],
        query: db.selectFrom("lists").selectAll(),
        parameters: []
    });`

**Comment by Chriztiaan** [comment]
Hey @rizalalfandi123, thanks for reporting this.
Could you please give more information? Does it break on runtime, or is there type errors?

**Comment by rizalalfandi123** [comment]
Yes, it breaks at runtime, especially in the React lifecycle.
The parameters can be undefined, but TypeScript doesn't warn about it.

![image](https://github.com/user-attachments/assets/a96b8ce4-2e68-453f-a2d7-da44ef4c2615)


https://github.com/powersync-ja/powersync-js/blob/7e23d6519a12b66a96d6059cd479a516e2128749/packages/tanstack-react-query/src/hooks/useQuery.ts#L83

then set error in catch and maybe trigger error lifecycle

https://github.com/powersync-ja/powersync-js/blob/7e23d6519a12b66a96d6059cd479a516e2128749/packages/tanstack-react-query/src/hooks/useQuery.ts#L88

@Chriztiaan

**Comment by Chriztiaan** [comment]
Thank you for the information, will look at it asap.

**Comment by Chriztiaan** [comment]
Hey @rizalalfandi123, could you retest with this version: `@powersync/tanstack-react-query@0.0.9`?

**Comment by rizalalfandi123** [comment]
Solved
