### ISSUE TITLE
Watching Drizzle "with"-queries, not supported?

### ISSUE THREAD

**Issue by steveninety** [powersync-ja/powersync-js#426]
Doing a Drizzle watched query [as per the docs](https://docs.powersync.com/client-sdk-references/javascript-web/javascript-orm/drizzle#watched-queries), but instead of `db.select()`, using `db.query.findMany({ with: { someRelationName: true }})`, will result in all relations being returned (1) as JSON and (2) as an array of arrays of object-values instead of just... an array of objects.

Am I tapping into an unsupported feature, or is this a bug?

**Comment by steveninety** [comment]
Thanks Christiaan! Let's close this issue as soon as the update rolls out.

**Comment by Chriztiaan** [comment]
Hey @steveninety, `@powersync/drizzle-driver@0.2.0` has been released which addresses this problem.
Documentation available for the new watch function on the DrizzleDb here: https://docs.powersync.com/client-sdk-references/javascript-web/javascript-orm/drizzle#watched-queries

**Comment by steveninety** [comment]
Thank you for the quick work! I just had time to test things out and so far so good, lots of boilerplate gone! And being able to call .watch on the drizzle db instead of the powersync db clears up a possible point of confusion too.

I just see one mistake which is that the result parameter in onResult is inferred as an {}[] in .findFirst() and a {}[][] in .findMany(). Whereas findFirst does indeed return an {}[], the findMany also returns an {}[] and not an {}[][]. Beside that, I think it's fair to assume that they should have been an {} and {}[] in findFirst and findMany respectively. But I can work around it for now!

**Comment by steveninety** [comment]
Fixed by #430 
Thanks!

> I just see one mistake which is that the result parameter in onResult is inferred as an {}[] in .findFirst() and a {}[][] in .findMany(). Whereas findFirst does indeed return an {}[], the findMany also returns an {}[] and not an {}[][]. Beside that, I think it's fair to assume that they should have been an {} and {}[] in findFirst and findMany respectively. But I can work around it for now!
