### ISSUE TITLE
Support Kysely driver in React `@journeyapps/powersync-react` and `@journeyapps/powersync-react-native`

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/powersync-js#92]
Right now hooks like `usePowerSyncWatchedQuery` only support strings.

```ts
export declare const usePowerSyncWatchedQuery: <T = any>(sqlStatement: string, parameters?: any[], options?: Omit<SQLWatchOptions, 'signal'>) => T[];
```

I expect to pass a Kysely query like `db.selectFrom('quotes').selectAll().execute()`. I'm new with SQL and Kysely, I'm not sure if passing `execute` is good.

```ts
export const db = wrapPowerSyncWithKysely<Database>(powerSync)
const selectAll = db.selectFrom('quotes').selectAll().execute()
...
usePowerSyncWatchedQuery(selectAll)
```

**Comment by guillempuche** [comment]
@stevensJourney, will you plan to work on this?

**Comment by stevensJourney** [comment]
@guillempuche We are currently tracking this. There are plans to release a major update to our React hooks package in the near future. This update is to align the React hooks APIs with our recently released Vue composables by returning additional state information. This is still in the works, but could also potentially include the changes listed here. 

We will keep you updated 🙏

**Comment by DominicGBauer** [comment]
Hi @guillempuche this should now be resolved in the latest release of the react package v1.3.0 :)

**Comment by guillempuche** [comment]
@DominicGBauer, good job!
